import * as XLSX from "xlsx";

export type SaleRow={period:string;channel:string;base:string;grade:string;manager:string;senior:string;name:string;entryDate:Date|null;orders:number;revenue:number;arrival:number|null;attendance:number|null;completion:number|null;dealPeople:number;dealOrders:number;roi:number|null};
export type LoadedBook={id:string;name:string;period:string;channel:string;rows:SaleRow[];sheetNames:string[];warnings:string[]};
export type Metric={orders:number;revenue:number;ltv:number;arrival:number|null;attendance:number|null;completion:number|null;headConv:number;timesConv:number;people:number;zero:number};
export type GradeLine={base:string;grade:string;orders:number;share:number;newcomers:number;people:number;newcomerRate:number;ltv:number;attendance:number|null};
export type CohortLine={people:number;orders:number;ltv:number;headConv:number;zero:number};
export type ManagerDirection="up"|"down"|"flat";
export type ManagerLine={name:string;base:string;grade:string;orders:number;share:number;ltv:number;previousLtv:number;arrival:number|null;attendance:number|null;completion:number|null;headConv:number;previousHeadConv:number;zero:number;people:number;newcomers:number;newcomerZero:number;continuing:number;top2Share:number;impact:number;repeatDrag:boolean;cohort2:CohortLine;cohort3:CohortLine|null;newTeam:CohortLine;diagnosis:string;action?:string;direction?:ManagerDirection};
export type ReviewResult={channel:string;currentPeriod:string;previousPeriod:string;current:Metric;previous:Metric;gradeLines:GradeLine[];managers:ManagerLine[];trend:{period:string;bases:Record<string,number>}[];bases:string[];summary:string;userText:string;salesText:string;fullText:string;warnings:string[]};

const clean=(v:unknown)=>String(v??"").replace(/[\s\n\r（）()【】_－—–\-：:/／|｜·•]/g,"").replace(/\[|\]/g,"").toLowerCase();
const num=(v:unknown)=>{if(v==null||v==="")return 0;const n=Number(String(v).replace(/,/g,"").replace(/%/g,""));return Number.isFinite(n)?n:0};
const rate=(v:unknown):number|null=>{if(v==null||v==="")return null;const s=String(v);let n=num(v);if(s.includes("%")||n>1)n/=100;return Number.isFinite(n)?n:null};
const aliases:Record<string,string[]>={name:["销售姓名","销售名字","销售人员","顾问姓名","班主任姓名","学管姓名","name","姓名","销售"],base:["所属细分基地","细分基地","所属基地","基地","城市","中心","区域"],grade:["所属年级","年级","学段"],manager:["直属销售经理","销售经理","直属经理","经理","组长"],senior:["高级经理","大区经理","高经"],entryDate:["entrydate","入职时间","入职日期","入职date"],orders:["低价课成单人数","低价课成单量","低价课订单量","低价成单量","低价课用户数","低价课人数","总成单量","成单用户数","成单数量","承接用户数","总承接量","成单量","承接量","接单量","订单量","订单数","用户量","单量"],revenue:["正价课实收金额","正价课金额","实收金额","营收","收入","gmv","业绩"],ltv:["ltv","用户价值"],arrival:["到课率","到课"],attendance:["出勤率","出勤"],completion:["完课率","完课"],dealPeople:["出单人数","成交人数","破壳人数"],dealOrders:["出单单数","成交单数","人次"],headConv:["人头转化率","破壳率","人头转化"],timesConv:["人次转化率","人次转化"],roi:["roi"]};
const findKey=(headers:string[],key:string)=>{const names=aliases[key].map(clean).sort((a,b)=>b.length-a.length);for(const name of names){const exact=headers.find(h=>clean(h)===name);if(exact)return exact}for(const name of names){const partial=headers.find(h=>clean(h).includes(name));if(partial)return partial}};
const validName=(s:string)=>s&&!/^(总计|合计|小计|无|空|销售)$/.test(s.trim());
const inferPeriod=(name:string)=>{const compact=name.replace(/\s/g,"");const toPeriod=(mm:string,dd:string)=>{const month=Number(mm),day=Number(dd);return month>=1&&month<=12&&day>=1&&day<=31?`${String(month).padStart(2,"0")}${String(day).padStart(2,"0")}期`:null};
 const marked=compact.match(/(?:20\d{2}[年._\-/]?)?(\d{1,2})月(\d{1,2})(?:日|期)?/);if(marked){const p=toPeriod(marked[1],marked[2]);if(p)return p}
 const separated=compact.match(/(?:20\d{2}[-_/])?(\d{1,2})[-_/](\d{1,2})(?:日|期)?/);if(separated){const p=toPeriod(separated[1],separated[2]);if(p)return p}
 const four=compact.match(/(?:^|[^\d])(?:20)?(\d{2})(\d{2})(?:日|期)?(?:$|[^\d])/);if(four){const p=toPeriod(four[1],four[2]);if(p)return p}return "未知期"};
const inferChannel=(name:string)=>{const s=clean(name);if(s.includes("cpa0转9")||s.includes("0转9")||s.includes("cpa09"))return "CPA0转9渠道";if(s.includes("cpa1元")||s.includes("1元")||s.includes("cpa1yuan")||s.includes("1yuan"))return "CPA1元渠道";if(s.includes("cpa19")||s.includes("19元"))return "CPA19渠道";return "未识别渠道"};
const gradeOrder=(grade:string)=>{const s=clean(grade);if(/高一|高1|一年级|1年级/.test(s))return 1;if(/高二|高2|二年级|2年级/.test(s))return 2;if(/高三|高3|三年级|3年级/.test(s))return 3;return 99};
const periodDate=(p:string)=>{const m=p.match(/(\d{2})(\d{2})/);return m?new Date(2026,Number(m[1])-1,Number(m[2])):new Date()};
const parseDate=(v:unknown):Date|null=>{if(v instanceof Date)return v;if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?new Date(d.y,d.m-1,d.d):null}const s=String(v??"").trim();if(!s)return null;const d=new Date(s.replace(/[年月]/g,"-").replace("日",""));return Number.isNaN(d.getTime())?null:d};
const mergedHeaders=(matrix:unknown[][],end:number)=>{const rows=matrix.slice(Math.max(0,end-2),end+1),width=Math.max(0,...rows.map(row=>row.length));return Array.from({length:width},(_,column)=>rows.map(row=>String(row[column]??"").trim()).filter((value,index,values)=>Boolean(value)&&values.indexOf(value)===index).join(" "))};

export async function parseWorkbook(file:File):Promise<LoadedBook>{
 const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const rows:SaleRow[]=[];const warnings:string[]=[];const matrices=wb.SheetNames.map(sheetName=>({sheetName,matrix:XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName],{header:1,defval:"",raw:true})}));
 const sourceHint=[file.name,...wb.SheetNames,...matrices.flatMap(x=>x.matrix.slice(0,12).flatMap(r=>r).map(String))].join(" ");const period=inferPeriod(sourceHint);const channel=inferChannel(sourceHint);
 for(const {matrix} of matrices){let headerIndex=-1;let headers:string[]=[];
  for(let i=0;i<Math.min(matrix.length,100);i++){const hs=mergedHeaders(matrix,i);if(findKey(hs,"name")&&findKey(hs,"orders")){headerIndex=i;headers=hs;break}}
  if(headerIndex<0)continue;const keys={name:findKey(headers,"name"),base:findKey(headers,"base"),grade:findKey(headers,"grade"),manager:findKey(headers,"manager"),senior:findKey(headers,"senior"),entryDate:findKey(headers,"entryDate"),orders:findKey(headers,"orders"),revenue:findKey(headers,"revenue"),ltv:findKey(headers,"ltv"),arrival:findKey(headers,"arrival"),attendance:findKey(headers,"attendance"),completion:findKey(headers,"completion"),dealPeople:findKey(headers,"dealPeople"),dealOrders:findKey(headers,"dealOrders"),headConv:findKey(headers,"headConv"),timesConv:findKey(headers,"timesConv"),roi:findKey(headers,"roi")};
  const carry={base:"",grade:"",manager:"",senior:""};for(let i=headerIndex+1;i<matrix.length;i++){const a=matrix[i]||[];const obj:Record<string,unknown>={};headers.forEach((h,j)=>obj[h]=a[j]);for(const k of ["base","grade","manager","senior"] as const){const h=keys[k];const v=h?String(obj[h]??"").trim():"";if(v)carry[k]=v}
   const name=keys.name?String(obj[keys.name]??"").trim():"";if(!validName(name))continue;const orders=num(keys.orders?obj[keys.orders]:0);const ltv=num(keys.ltv?obj[keys.ltv]:0);const revenue=keys.revenue?num(obj[keys.revenue]):orders*ltv;const dealPeople=keys.dealPeople?num(obj[keys.dealPeople]):keys.headConv?orders*(rate(obj[keys.headConv])??0):revenue>0?1:0;const dealOrders=keys.dealOrders?num(obj[keys.dealOrders]):keys.timesConv?orders*(rate(obj[keys.timesConv])??0):dealPeople;
   rows.push({period,channel,base:carry.base||"未识别基地",grade:carry.grade||"未识别年级",manager:carry.manager||"未识别经理",senior:carry.senior,name,entryDate:parseDate(keys.entryDate?obj[keys.entryDate]:null),orders,revenue,arrival:rate(keys.arrival?obj[keys.arrival]:null),attendance:rate(keys.attendance?obj[keys.attendance]:null),completion:rate(keys.completion?obj[keys.completion]:null),dealPeople,dealOrders,roi:rate(keys.roi?obj[keys.roi]:null)});
  }
 }
 if(period==="未知期")warnings.push("未识别到期次：请在文件名、工作表名或表格标题中写入如“0813期”");if(channel==="未识别渠道")warnings.push("未识别到渠道：仍可生成复盘；建议在文件名或工作表名写入 CPA0转9、CPA1元 或 CPA19");if(!rows.length)warnings.push("未找到同时包含销售姓名和成单量的明细表；支持的表头包括“销售/姓名”和“成单量/承接量/订单量”");if(rows.some(r=>r.revenue===0)&&!rows.some(r=>r.revenue>0))warnings.push("未识别到营收或LTV列，无法计算真实LTV");
 return{id:`${file.name}-${file.size}-${file.lastModified}`,name:file.name,period,channel,rows,sheetNames:wb.SheetNames,warnings};
}

const metric=(rows:SaleRow[]):Metric=>{const orders=rows.reduce((s,r)=>s+r.orders,0),revenue=rows.reduce((s,r)=>s+r.revenue,0);const weighted=(k:"arrival"|"attendance"|"completion")=>{const v=rows.filter(r=>r[k]!=null&&r.orders>0),d=v.reduce((s,r)=>s+r.orders,0);return d?v.reduce((s,r)=>s+(r[k]??0)*r.orders,0)/d:null};const people=new Set(rows.map(r=>r.name)).size;const bySales=new Map<string,number>();rows.forEach(r=>bySales.set(r.name,(bySales.get(r.name)||0)+r.revenue));return{orders,revenue,ltv:orders?revenue/orders:0,arrival:weighted("arrival"),attendance:weighted("attendance"),completion:weighted("completion"),headConv:orders?rows.reduce((s,r)=>s+r.dealPeople,0)/orders:0,timesConv:orders?rows.reduce((s,r)=>s+r.dealOrders,0)/orders:0,people,zero:[...bySales.values()].filter(v=>v===0).length}};
const newcomer=(r:SaleRow,p:string,days:number)=>{if(!r.entryDate)return false;const diff=(periodDate(p).getTime()-r.entryDate.getTime())/86400000;return diff>=0&&diff<=days};
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):"0.0";const pct=(n:number|null,d=1)=>n==null?"—":`${(n*100).toFixed(d)}%`;const pp=(n:number|null)=>n==null?"—":`${n>=0?"+":""}${(n*100).toFixed(1)}pp`;

const guidance=(cm:Metric,pm:Metric,current:Metric,opts:{direction:ManagerDirection;repeatDrag:boolean;zero:number;people:number;newcomers:number;newcomerZero:number;top2Share:number})=>{
 const arrivalGap=cm.arrival==null||current.arrival==null?null:cm.arrival-current.arrival,attendanceGap=cm.attendance==null||current.attendance==null?null:cm.attendance-current.attendance,completionGap=cm.completion==null||current.completion==null?null:cm.completion-current.completion,headGap=cm.headConv-current.headConv;
 const evidence=[`到课${pct(cm.arrival)}（较大盘${pp(arrivalGap)}）`,`出勤${pct(cm.attendance)}（较大盘${pp(attendanceGap)}）`,`完课${pct(cm.completion)}（较大盘${pp(completionGap)}）`,`人头${pct(cm.headConv,2)}（较大盘${pp(headGap)}）`].join("、");let diagnosis="",action="";
 if(arrivalGap!=null&&arrivalGap<-.05){diagnosis=`过程证据：${evidence}。当前最大断点在到课前，${opts.direction==="up"?"LTV提升尚未传导到前端触达":"前端触达走弱直接压缩了后续有效触点"}。`;action="逐条抽查首次触达、课程价值塑造和开课前提醒；经理每日拉取未到课名单，完成二次召回并验收到课率。"}
 else if(attendanceGap!=null&&attendanceGap<-.05){diagnosis=`过程证据：${evidence}。到课后出勤低于大盘，主要要查临开课提醒、时间异议处理和召回。`;action="按开课前节点检查提醒记录，对未出勤客户当天完成电话/私聊召回；经理抽查异议标签和召回结果。"}
 else if(completionGap!=null&&completionGap<-.05){diagnosis=`过程证据：${evidence}。出勤后完课不足，课中陪伴和掉线召回是优先核验点。`;action="为低完课销售安排课中陪谈，补齐互动、掉线召回和需求记录；次日复盘未完课名单及后续转化。"}
 else if(completionGap==null||completionGap>-.02){
  if(headGap<-.005){diagnosis=`过程证据：${evidence}。完课已接近大盘但人头转化偏低，断点更靠后，不能把问题归因于到课。`;action="逐个抽查测评解读、需求诊断、家长链接、方案输出、异议处理和48小时追单记录；经理安排陪谈并逐单验收。"}
  else if(opts.newcomerZero>0&&opts.people>0&&opts.zero/opts.people>.5){diagnosis=`过程证据：${evidence}；${opts.zero}/${opts.people}人挂0，其中新人${opts.newcomerZero}/${opts.newcomers}人。团队产出可能被新人爬坡和带教覆盖不足拖累。`;action="新人首3天完成产品与录音训练，首周至少安排经理陪谈；晨会拆解Top成交链路，逐人验收首触、测评和追单节点。"}
  else if(opts.top2Share>.6){diagnosis=`过程证据：${evidence}；Top2营收占比${pct(opts.top2Share)}。当前变化主要由少数销售贡献，团队复制性仍需验证。`;action="要求Top2各提交一条完整成交链路，由经理在晨会拆解并让其余销售跟练；对跟练客户按破壳、客单和追单结果验收。"}
  else if(opts.direction==="up"&&cm.headConv>pm.headConv){diagnosis=`过程证据：${evidence}；人头转化较上期${pp(cm.headConv-pm.headConv)}，与LTV提升方向一致。`;action="复盘该团队的测评解读、需求诊断、方案输出和追单原话，沉淀成可复制话术并让其他销售跟练。"}
  else if(opts.direction==="down"){diagnosis=`过程证据：${evidence}；LTV下滑但前端漏斗未出现单一明显断点，需继续核对课后成交与客单结构。`;action="逐单核对未成交原因、客单和产品组合，补查完课后方案输出、异议处理及持续追单记录；经理每日报未成交清单。"}
  else {diagnosis=`过程证据：${evidence}；未发现单一过程指标足以解释变化，需结合成交明细确认。`;action="抽查Top成交与未成交各3单，按需求诊断、方案输出、异议处理、追单和产品组合逐项对照，沉淀可复制动作。"}
 } else {diagnosis=`过程证据：${evidence}；过程指标整体偏弱，需先排查前端与课中执行。`;action="按到课、出勤、完课顺序抽查过程记录，建立经理每日异常名单和次日复盘机制。"}
 if(opts.repeatDrag){diagnosis=`连续两期LTV下滑。${diagnosis}`;action="在上述动作外，连续两期跟踪同一批承接销售，经理每周复盘陪谈覆盖、追单覆盖和Top打法复制结果。"}
 return{diagnosis,action};
};

export function buildReview(books:LoadedBook[],currentPeriod:string,previousPeriod:string,channel:string,newcomerDays=50):ReviewResult{
 const relevant=books.filter(b=>channel==="全部渠道"||b.channel===channel),curRows=relevant.filter(b=>b.period===currentPeriod).flatMap(b=>b.rows),preRows=relevant.filter(b=>b.period===previousPeriod).flatMap(b=>b.rows);if(!curRows.length)throw new Error("本期没有可分析的销售明细");
 const current=metric(curRows),previous=metric(preRows),bases=[...new Set(curRows.map(r=>r.base))].filter(Boolean),grades=[...new Set(curRows.map(r=>r.grade))].filter(Boolean).sort((a,b)=>gradeOrder(a)-gradeOrder(b)||a.localeCompare(b,"zh-CN"));
 const gradeLines:GradeLine[]=[];for(const base of bases){const br=curRows.filter(r=>r.base===base),bm=metric(br);for(const grade of grades){const rs=br.filter(r=>r.grade===grade);if(!rs.length)continue;const sales=new Map<string,SaleRow>();rs.forEach(r=>{if(!sales.has(r.name)||(!sales.get(r.name)?.entryDate&&r.entryDate))sales.set(r.name,r)});const newcomers=[...sales.values()].filter(r=>newcomer(r,currentPeriod,newcomerDays)).length;const m=metric(rs);gradeLines.push({base,grade,orders:m.orders,share:bm.orders?m.orders/bm.orders:0,newcomers,people:sales.size,newcomerRate:sales.size?newcomers/sales.size:0,ltv:m.ltv,attendance:m.attendance})}const sales=new Map<string,SaleRow>();br.forEach(r=>{if(!sales.has(r.name)||(!sales.get(r.name)?.entryDate&&r.entryDate))sales.set(r.name,r)});const n=[...sales.values()].filter(r=>newcomer(r,currentPeriod,newcomerDays)).length;gradeLines.push({base,grade:"总计",orders:bm.orders,share:1,newcomers:n,people:sales.size,newcomerRate:sales.size?n/sales.size:0,ltv:bm.ltv,attendance:bm.attendance})}
 gradeLines.sort((a,b)=>a.base.localeCompare(b.base,"zh-CN")||((a.grade==="总计"?100:gradeOrder(a.grade))-(b.grade==="总计"?100:gradeOrder(b.grade)))||a.grade.localeCompare(b.grade,"zh-CN"));
 const periodList=[...new Set(relevant.map(b=>b.period))].sort((a,b)=>a.localeCompare(b)),previousPrevious=periodList[periodList.indexOf(previousPeriod)-1],previousPreviousRows=previousPrevious?relevant.filter(b=>b.period===previousPrevious).flatMap(b=>b.rows):[];
 const cohortMetric=(rows:SaleRow[],names:Set<string>):CohortLine=>{const rs=rows.filter(r=>names.has(r.name)),m=metric(rs);return{people:names.size,orders:m.orders,ltv:m.ltv,headConv:m.headConv,zero:m.zero}};
 const managerKeys=[...new Set(curRows.map(r=>`${r.base}|||${r.manager}`))];
 const managerRows:ManagerLine[]=managerKeys.map(key=>{const[base,name]=key.split("|||"),cr=curRows.filter(r=>r.base===base&&r.manager===name),pr=preRows.filter(r=>r.base===base&&r.manager===name),ppr=previousPreviousRows.filter(r=>r.base===base&&r.manager===name),cm=metric(cr),pm=metric(pr),ppm=metric(ppr),baseOrders=metric(curRows.filter(r=>r.base===base)).orders;const curSales=[...new Set(cr.map(r=>r.name))],preSales=new Set(pr.map(r=>r.name)),ppSales=new Set(ppr.map(r=>r.name)),continuing2=new Set(curSales.filter(n=>preSales.has(n))),continuing3=previousPrevious?new Set(curSales.filter(n=>preSales.has(n)&&ppSales.has(n))):null,newTeam=new Set(curSales.filter(n=>!preSales.has(n))),newSales=curSales.filter(n=>cr.some(r=>r.name===n&&newcomer(r,currentPeriod,newcomerDays))),newcomerZero=newSales.filter(n=>cr.filter(r=>r.name===n).reduce((s,r)=>s+r.revenue,0)===0).length;const salesRevenue=curSales.map(n=>cr.filter(r=>r.name===n).reduce((s,r)=>s+r.revenue,0)).sort((a,b)=>b-a),top2=salesRevenue.slice(0,2).reduce((a,b)=>a+b,0),ltvDelta=cm.ltv-pm.ltv,direction:ManagerDirection=ltvDelta>0?"up":ltvDelta<0?"down":"flat",repeatDrag=Boolean(previousPrevious&&cm.ltv<pm.ltv&&pm.ltv<ppm.ltv),help=guidance(cm,pm,current,{direction,repeatDrag,zero:cm.zero,people:cm.people,newcomers:newSales.length,newcomerZero,top2Share:cm.revenue?top2/cm.revenue:0});return{name,base,grade:[...new Set(cr.map(r=>r.grade))].join("/"),orders:cm.orders,share:baseOrders?cm.orders/baseOrders:0,ltv:cm.ltv,previousLtv:pm.ltv,arrival:cm.arrival,attendance:cm.attendance,completion:cm.completion,headConv:cm.headConv,previousHeadConv:pm.headConv,zero:cm.zero,people:cm.people,newcomers:newSales.length,newcomerZero,continuing:continuing2.size,top2Share:cm.revenue?top2/cm.revenue:0,impact:cm.orders*ltvDelta,repeatDrag,cohort2:cohortMetric(cr,continuing2),cohort3:continuing3?cohortMetric(cr,continuing3):null,newTeam:cohortMetric(cr,newTeam),diagnosis:help.diagnosis,action:help.action,direction}});
 const delta=current.ltv-previous.ltv,isImproving=delta>15,isDeclining=delta< -15,managerGroup=(m:ManagerLine)=>isImproving?(m.direction==="up"?0:m.direction==="flat"?1:2):isDeclining?(m.direction==="down"?0:m.direction==="flat"?1:2):0,impactSort=(a:ManagerLine,b:ManagerLine)=>Math.abs(b.impact)-Math.abs(a.impact)||b.share-a.share||Math.abs(b.ltv-b.previousLtv)-Math.abs(a.ltv-a.previousLtv),managers=managerRows.sort((a,b)=>managerGroup(a)-managerGroup(b)||impactSort(a,b));
 const baseMetrics=bases.map(base=>({base,c:metric(curRows.filter(r=>r.base===base)),p:metric(preRows.filter(r=>r.base===base))})).sort((a,b)=>(b.c.ltv-b.p.ltv)-(a.c.ltv-a.p.ltv));const positiveManagers=managers.filter(m=>m.impact>0),negativeManagers=managers.filter(m=>m.impact<0),ordered=(list:ManagerLine[])=>list.slice().sort(impactSort),drivers=ordered(isImproving?positiveManagers:isDeclining?negativeManagers:[]),leader=drivers[0];
 const primaryBase=isImproving?baseMetrics.find(x=>x.c.ltv>x.p.ltv):isDeclining?[...baseMetrics].reverse().find(x=>x.c.ltv<x.p.ltv):undefined;const positiveLeader=ordered(positiveManagers)[0],negativeLeader=ordered(negativeManagers)[0],positiveBase=baseMetrics.find(x=>x.c.ltv>x.p.ltv),negativeBase=[...baseMetrics].reverse().find(x=>x.c.ltv<x.p.ltv);
 const processDelta=(c:number|null,p:number|null)=>c==null||p==null?null:c-p,teamLabel=(name:string)=>name.endsWith("团队")?name:`${name}团队`;
 const summary=isImproving?`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）提升${fmt(delta)}，核心拉动来自${primaryBase?primaryBase.base:"各基地"}；经理区先看正向增量团队，再按影响规模和单量占比核验可复制动作。`:isDeclining?`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）下滑${fmt(Math.abs(delta))}，${primaryBase?`主要拖累来自${primaryBase.base}；经理区先看负向拖累团队，再按影响规模和单量占比定位断点。`:`未识别到基地LTV下滑，整体回落更可能来自年级或团队承接结构变化，需核查单量迁移。`}`:`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）基本持平（差值${fmt(Math.abs(delta))}），${positiveBase&&negativeBase?`${positiveBase.base}LTV回升（${fmt(positiveBase.p.ltv)} → ${fmt(positiveBase.c.ltv)}）与${negativeBase.base}LTV回落（${fmt(negativeBase.p.ltv)} → ${fmt(negativeBase.c.ltv)}）相互抵消。`:positiveBase?`${positiveBase.base}回升是主要正向变化，其他基地基本抵消。`:negativeBase?`${negativeBase.base}回落是主要负向变化，其他基地基本抵消。`:"各基地变化有限，继续观察年级和团队分化。"}`;
 const processChanges=[["到课率",processDelta(current.arrival,previous.arrival)],["出勤率",processDelta(current.attendance,previous.attendance)],["完课率",processDelta(current.completion,previous.completion)] as const],improvedProcess=processChanges.filter(([,v])=>v!=null&&v>0.005).map(([name,v])=>`${name}+${(v!*100).toFixed(1)}pp`).join("、"),declinedProcess=processChanges.filter(([,v])=>v!=null&&v< -0.005).map(([name,v])=>`${name}${(v!*100).toFixed(1)}pp`).join("、");
 const userText=isImproving?`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。${improvedProcess?`${improvedProcess}，为课后转化提供了更多有效触点。`:declinedProcess?`前端过程未同步改善（${declinedProcess}），本期提升更可能来自课后成交效率或产品组合，需结合录音、追单与客单数据验证。`:"前端过程基本稳定，提升原因应继续下探至课后破壳和关单动作。"}`:isDeclining?`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。${declinedProcess?`过程回落集中在${declinedProcess}，需优先检查首次触达、课程价值塑造与开课提醒。`:"前端过程未明显恶化，问题更可能集中在完课后的破壳与关单。"}`:`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。整体基本持平不代表内部无变化，应结合回升/下滑基地分别检查前端承接与课后破壳，避免正负变化被整体均值掩盖。`;
 const salesText=leader?isImproving?`${leader.base}${teamLabel(leader.name)}是本期核心增量：LTV（${fmt(leader.previousLtv)} → ${fmt(leader.ltv)}），人头转化（${pct(leader.previousHeadConv,2)} → ${pct(leader.headConv,2)}），承接基地${pct(leader.share)}单量。${leader.diagnosis}具体动作：${leader.action}`:`${leader.base}${teamLabel(leader.name)}是本期主要拖累：LTV（${fmt(leader.previousLtv)} → ${fmt(leader.ltv)}），人头转化（${pct(leader.previousHeadConv,2)} → ${pct(leader.headConv,2)}），承接基地${pct(leader.share)}单量，${leader.people}人中${leader.zero}人挂0，其中新人${leader.newcomers}人、新人挂0 ${leader.newcomerZero}人。${leader.diagnosis}具体动作：${leader.action}`:isDeclining?"经理团队LTV均未下滑，不能归因为单个团队拖累；整体回落更可能由低LTV年级/团队承接量上升或上期高LTV团队单量收缩导致，需优先核查承接结构。":positiveLeader&&negativeLeader?`整体基本持平，但内部由正负团队对冲：${positiveLeader.base}${teamLabel(positiveLeader.name)}回升（LTV ${fmt(positiveLeader.previousLtv)} → ${fmt(positiveLeader.ltv)}，承接${pct(positiveLeader.share)}单量）是主要正向贡献；${negativeLeader.base}${teamLabel(negativeLeader.name)}下滑（LTV ${fmt(negativeLeader.previousLtv)} → ${fmt(negativeLeader.ltv)}，承接${pct(negativeLeader.share)}单量）是主要拖累。需分别复盘前者的可复制打法与后者的漏斗断点。`:positiveLeader?`${positiveLeader.base}${teamLabel(positiveLeader.name)}回升（LTV ${fmt(positiveLeader.previousLtv)} → ${fmt(positiveLeader.ltv)}）是本期主要正向变化；尚未识别明确下滑团队，需结合承接结构继续核查。`:negativeLeader?`${negativeLeader.base}${teamLabel(negativeLeader.name)}下滑（LTV ${fmt(negativeLeader.previousLtv)} → ${fmt(negativeLeader.ltv)}）是本期主要负向变化；尚未识别明确回升团队，需结合承接结构继续核查。`:"整体LTV差值在15以内，团队变化也有限，继续观察下期变化。";
 const fullText=`整体数据总结：${summary}\n\n用户侧：${userText}\n\n销售侧：${salesText}`;const allPeriods=[...new Set(relevant.map(b=>b.period))].sort((a,b)=>a.localeCompare(b)).slice(-6),trend=allPeriods.map(period=>({period,bases:Object.fromEntries(bases.map(base=>[base,metric(relevant.filter(b=>b.period===period).flatMap(b=>b.rows).filter(r=>r.base===base)).ltv]))}));
 return{channel,currentPeriod,previousPeriod,current,previous,gradeLines,managers:managers.slice(0,8),trend,bases,summary,userText,salesText,fullText,warnings:[...new Set(relevant.flatMap(b=>b.warnings))]};
}

export const format={number:(n:number)=>Math.round(n).toLocaleString("zh-CN"),decimal:(n:number)=>fmt(n),percent:(n:number|null,d=1)=>pct(n,d)};
