import * as XLSX from "xlsx";

export type SaleRow={period:string;channel:string;base:string;grade:string;manager:string;senior:string;name:string;entryDate:Date|null;orders:number;revenue:number;arrival:number|null;attendance:number|null;completion:number|null;dealPeople:number;dealOrders:number;roi:number|null};
export type LoadedBook={id:string;name:string;period:string;channel:string;rows:SaleRow[];sheetNames:string[];warnings:string[]};
export type Metric={orders:number;revenue:number;ltv:number;arrival:number|null;attendance:number|null;completion:number|null;headConv:number;timesConv:number;people:number;zero:number};
export type GradeLine={base:string;grade:string;orders:number;share:number;newcomers:number;people:number;newcomerRate:number;ltv:number;attendance:number|null};
export type CohortLine={people:number;orders:number;ltv:number;headConv:number;zero:number};
export type ManagerLine={name:string;base:string;grade:string;orders:number;share:number;ltv:number;previousLtv:number;arrival:number|null;attendance:number|null;completion:number|null;headConv:number;previousHeadConv:number;zero:number;people:number;newcomers:number;newcomerZero:number;continuing:number;top2Share:number;impact:number;repeatDrag:boolean;cohort2:CohortLine;cohort3:CohortLine|null;newTeam:CohortLine;diagnosis:string};
export type ReviewResult={channel:string;currentPeriod:string;previousPeriod:string;current:Metric;previous:Metric;gradeLines:GradeLine[];managers:ManagerLine[];trend:{period:string;bases:Record<string,number>}[];bases:string[];summary:string;userText:string;salesText:string;fullText:string;warnings:string[]};

const clean=(v:unknown)=>String(v??"").replace(/[\s\n\r（）()【】\[\]_－—–\-：:]/g,"").toLowerCase();
const num=(v:unknown)=>{if(v==null||v==="")return 0;const n=Number(String(v).replace(/,/g,"").replace(/%/g,""));return Number.isFinite(n)?n:0};
const rate=(v:unknown):number|null=>{if(v==null||v==="")return null;const s=String(v);let n=num(v);if(s.includes("%")||n>1)n/=100;return Number.isFinite(n)?n:null};
const aliases:Record<string,string[]>={name:["name","销售姓名","顾问姓名","班主任姓名","销售名字","姓名","销售"],base:["所属基地","基地","城市","中心","区域"],grade:["所属年级","年级","学段"],manager:["直属销售经理","销售经理","直属经理","经理","组长"],senior:["高级经理","大区经理","高经"],entryDate:["entrydate","入职时间","入职日期","入职date"],orders:["低价课成单量","低价成单量","低价课用户数","低价课人数","总成单量","成单量","承接量","接单量","订单量","用户量","单量"],revenue:["正价课实收金额","正价课金额","实收金额","营收","收入","gmv","业绩"],ltv:["ltv","用户价值"],arrival:["到课率","到课"],attendance:["出勤率","出勤"],completion:["完课率","完课"],dealPeople:["出单人数","成交人数","破壳人数"],dealOrders:["出单单数","成交单数","人次"],headConv:["人头转化率","破壳率","人头转化"],timesConv:["人次转化率","人次转化"],roi:["roi"]};
const findKey=(headers:string[],key:string)=>{const names=aliases[key].map(clean).sort((a,b)=>b.length-a.length);return headers.find(h=>names.includes(clean(h)))||headers.find(h=>names.some(a=>clean(h).includes(a)))};
const validName=(s:string)=>s&&!/^(总计|合计|小计|无|空|销售)$/.test(s.trim());
const inferPeriod=(name:string)=>{const compact=name.replace(/\s/g,"");const four=compact.match(/(?:20)?(\d{2})[年._\-/]?(\d{2})(?:日|期)?/);if(four){const mm=Number(four[1]),dd=Number(four[2]);if(mm>=1&&mm<=12&&dd>=1&&dd<=31)return `${String(mm).padStart(2,"0")}${String(dd).padStart(2,"0")}期`}return "未知期"};
const inferChannel=(name:string)=>{const s=clean(name);if(s.includes("cpa0转9")||s.includes("0转9")||s.includes("cpa09")||s.includes("09"))return "CPA0转9渠道";if(s.includes("cpa1元")||s.includes("1元")||s.includes("cpa1yuan")||s.includes("1yuan"))return "CPA1元渠道";if(s.includes("cpa19")||s.includes("19元"))return "CPA19渠道";return "未识别渠道"};
const gradeOrder=(grade:string)=>{const s=clean(grade);if(/高一|高1|一年级|1年级/.test(s))return 1;if(/高二|高2|二年级|2年级/.test(s))return 2;if(/高三|高3|三年级|3年级/.test(s))return 3;return 99};
const periodDate=(p:string)=>{const m=p.match(/(\d{2})(\d{2})/);return m?new Date(2026,Number(m[1])-1,Number(m[2])):new Date()};
const parseDate=(v:unknown):Date|null=>{if(v instanceof Date)return v;if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?new Date(d.y,d.m-1,d.d):null}const s=String(v??"").trim();if(!s)return null;const d=new Date(s.replace(/[年月]/g,"-").replace("日",""));return Number.isNaN(d.getTime())?null:d};

export async function parseWorkbook(file:File):Promise<LoadedBook>{
 const wb=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const rows:SaleRow[]=[];const warnings:string[]=[];const matrices=wb.SheetNames.map(sheetName=>({sheetName,matrix:XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName],{header:1,defval:"",raw:true})}));
 const sourceHint=[file.name,...wb.SheetNames,...matrices.flatMap(x=>x.matrix.slice(0,12).flatMap(r=>r).map(String))].join(" ");const period=inferPeriod(sourceHint);const channel=inferChannel(sourceHint);
 for(const {sheetName,matrix} of matrices){let headerIndex=-1;let headers:string[]=[];
  for(let i=0;i<Math.min(matrix.length,100);i++){const hs=(matrix[i]||[]).map(String);if(findKey(hs,"name")&&findKey(hs,"orders")){headerIndex=i;headers=hs;break}}
  if(headerIndex<0)continue;const keys={name:findKey(headers,"name"),base:findKey(headers,"base"),grade:findKey(headers,"grade"),manager:findKey(headers,"manager"),senior:findKey(headers,"senior"),entryDate:findKey(headers,"entryDate"),orders:findKey(headers,"orders"),revenue:findKey(headers,"revenue"),ltv:findKey(headers,"ltv"),arrival:findKey(headers,"arrival"),attendance:findKey(headers,"attendance"),completion:findKey(headers,"completion"),dealPeople:findKey(headers,"dealPeople"),dealOrders:findKey(headers,"dealOrders"),headConv:findKey(headers,"headConv"),timesConv:findKey(headers,"timesConv"),roi:findKey(headers,"roi")};
  let carry={base:"",grade:"",manager:"",senior:""};for(let i=headerIndex+1;i<matrix.length;i++){const a=matrix[i]||[];const obj:Record<string,unknown>={};headers.forEach((h,j)=>obj[h]=a[j]);for(const k of ["base","grade","manager","senior"] as const){const h=keys[k];const v=h?String(obj[h]??"").trim():"";if(v)carry[k]=v}
   const name=keys.name?String(obj[keys.name]??"").trim():"";if(!validName(name))continue;const orders=num(keys.orders?obj[keys.orders]:0);const ltv=num(keys.ltv?obj[keys.ltv]:0);const revenue=keys.revenue?num(obj[keys.revenue]):orders*ltv;const dealPeople=keys.dealPeople?num(obj[keys.dealPeople]):keys.headConv?orders*(rate(obj[keys.headConv])??0):revenue>0?1:0;const dealOrders=keys.dealOrders?num(obj[keys.dealOrders]):keys.timesConv?orders*(rate(obj[keys.timesConv])??0):dealPeople;
   rows.push({period,channel,base:carry.base||"未识别基地",grade:carry.grade||"未识别年级",manager:carry.manager||"未识别经理",senior:carry.senior,name,entryDate:parseDate(keys.entryDate?obj[keys.entryDate]:null),orders,revenue,arrival:rate(keys.arrival?obj[keys.arrival]:null),attendance:rate(keys.attendance?obj[keys.attendance]:null),completion:rate(keys.completion?obj[keys.completion]:null),dealPeople,dealOrders,roi:rate(keys.roi?obj[keys.roi]:null)});
  }
 }
 if(period==="未知期")warnings.push("未识别到期次：请在文件名、工作表名或表格标题中写入如“0813期”");if(channel==="未识别渠道")warnings.push("未识别到渠道：仍可生成复盘；建议在文件名或工作表名写入 CPA0转9、CPA1元 或 CPA19");if(!rows.length)warnings.push("未找到同时包含销售姓名和成单量的明细表；支持的表头包括“销售/姓名”和“成单量/承接量/订单量”");if(rows.some(r=>r.revenue===0)&&!rows.some(r=>r.revenue>0))warnings.push("未识别到营收或LTV列，无法计算真实LTV");
 return{id:`${file.name}-${file.size}-${file.lastModified}`,name:file.name,period,channel,rows,sheetNames:wb.SheetNames,warnings};
}

const metric=(rows:SaleRow[]):Metric=>{const orders=rows.reduce((s,r)=>s+r.orders,0),revenue=rows.reduce((s,r)=>s+r.revenue,0);const weighted=(k:"arrival"|"attendance"|"completion")=>{const v=rows.filter(r=>r[k]!=null&&r.orders>0),d=v.reduce((s,r)=>s+r.orders,0);return d?v.reduce((s,r)=>s+(r[k]??0)*r.orders,0)/d:null};const people=new Set(rows.map(r=>r.name)).size;const bySales=new Map<string,number>();rows.forEach(r=>bySales.set(r.name,(bySales.get(r.name)||0)+r.revenue));return{orders,revenue,ltv:orders?revenue/orders:0,arrival:weighted("arrival"),attendance:weighted("attendance"),completion:weighted("completion"),headConv:orders?rows.reduce((s,r)=>s+r.dealPeople,0)/orders:0,timesConv:orders?rows.reduce((s,r)=>s+r.dealOrders,0)/orders:0,people,zero:[...bySales.values()].filter(v=>v===0).length}};
const newcomer=(r:SaleRow,p:string,days:number)=>{if(!r.entryDate)return false;const diff=(periodDate(p).getTime()-r.entryDate.getTime())/86400000;return diff>=0&&diff<=days};
const fmt=(n:number,d=1)=>Number.isFinite(n)?n.toFixed(d):"0.0";const pct=(n:number|null,d=1)=>n==null?"—":`${(n*100).toFixed(d)}%`;

export function buildReview(books:LoadedBook[],currentPeriod:string,previousPeriod:string,channel:string,newcomerDays=50):ReviewResult{
 const relevant=books.filter(b=>channel==="全部渠道"||b.channel===channel);const curRows=relevant.filter(b=>b.period===currentPeriod).flatMap(b=>b.rows),preRows=relevant.filter(b=>b.period===previousPeriod).flatMap(b=>b.rows);if(!curRows.length)throw new Error("本期没有可分析的销售明细");
 const current=metric(curRows),previous=metric(preRows),bases=[...new Set(curRows.map(r=>r.base))].filter(Boolean),grades=[...new Set(curRows.map(r=>r.grade))].filter(Boolean).sort((a,b)=>gradeOrder(a)-gradeOrder(b)||a.localeCompare(b,"zh-CN"));
 const gradeLines:GradeLine[]=[];for(const base of bases){const br=curRows.filter(r=>r.base===base),bm=metric(br);for(const grade of grades){const rs=br.filter(r=>r.grade===grade);if(!rs.length)continue;const sales=new Map<string,SaleRow>();rs.forEach(r=>{if(!sales.has(r.name)||(!sales.get(r.name)?.entryDate&&r.entryDate))sales.set(r.name,r)});const newcomers=[...sales.values()].filter(r=>newcomer(r,currentPeriod,newcomerDays)).length;const m=metric(rs);gradeLines.push({base,grade,orders:m.orders,share:bm.orders?m.orders/bm.orders:0,newcomers,people:sales.size,newcomerRate:sales.size?newcomers/sales.size:0,ltv:m.ltv,attendance:m.attendance})}const sales=new Map<string,SaleRow>();br.forEach(r=>{if(!sales.has(r.name)||(!sales.get(r.name)?.entryDate&&r.entryDate))sales.set(r.name,r)});const n=[...sales.values()].filter(r=>newcomer(r,currentPeriod,newcomerDays)).length;gradeLines.push({base,grade:"总计",orders:bm.orders,share:1,newcomers:n,people:sales.size,newcomerRate:sales.size?n/sales.size:0,ltv:bm.ltv,attendance:bm.attendance})}
 const periodList=[...new Set(relevant.map(b=>b.period))].sort((a,b)=>a.localeCompare(b)),previousPrevious=periodList[periodList.indexOf(previousPeriod)-1],previousPreviousRows=previousPrevious?relevant.filter(b=>b.period===previousPrevious).flatMap(b=>b.rows):[];
 const cohortMetric=(rows:SaleRow[],names:Set<string>):CohortLine=>{const rs=rows.filter(r=>names.has(r.name)),m=metric(rs);return{people:names.size,orders:m.orders,ltv:m.ltv,headConv:m.headConv,zero:m.zero}};
 const managerKeys=[...new Set(curRows.map(r=>`${r.base}|||${r.manager}`))];const managers=managerKeys.map(key=>{const[base,name]=key.split("|||");const cr=curRows.filter(r=>r.base===base&&r.manager===name),pr=preRows.filter(r=>r.base===base&&r.manager===name),ppr=previousPreviousRows.filter(r=>r.base===base&&r.manager===name),cm=metric(cr),pm=metric(pr),ppm=metric(ppr),baseOrders=metric(curRows.filter(r=>r.base===base)).orders;const curSales=[...new Set(cr.map(r=>r.name))],preSales=new Set(pr.map(r=>r.name)),ppSales=new Set(ppr.map(r=>r.name)),continuing2=new Set(curSales.filter(n=>preSales.has(n))),continuing3=previousPrevious?new Set(curSales.filter(n=>preSales.has(n)&&ppSales.has(n))):null,newTeam=new Set(curSales.filter(n=>!preSales.has(n))),newSales=curSales.filter(n=>cr.some(r=>r.name===n&&newcomer(r,currentPeriod,newcomerDays))),newcomerZero=newSales.filter(n=>cr.filter(r=>r.name===n).reduce((s,r)=>s+r.revenue,0)===0).length;const salesRevenue=curSales.map(n=>cr.filter(r=>r.name===n).reduce((s,r)=>s+r.revenue,0)).sort((a,b)=>b-a),top2=salesRevenue.slice(0,2).reduce((a,b)=>a+b,0);const impact=cm.orders*(cm.ltv-pm.ltv),repeatDrag=Boolean(previousPrevious&&cm.ltv<pm.ltv&&pm.ltv<ppm.ltv);let diagnosis="";if(repeatDrag)diagnosis="连续两期LTV下滑，说明并非单期波动；需优先复盘经理过程追踪、关键节点陪谈与Top打法复制。";else if(cm.arrival!=null&&current.arrival!=null&&cm.arrival<current.arrival*.9)diagnosis="前端到课偏低，首次触达、课程价值塑造和开课提醒更可能是主要断点，需抽查SOP。";else if(cm.completion!=null&&current.completion!=null&&cm.completion>=current.completion*.95&&cm.headConv<current.headConv*.8)diagnosis="完课后破壳明显不足，需求诊断、方案输出、异议处理和持续追单需重点验证。";else if(cm.zero/cm.people>.5&&newcomerZero>0)diagnosis="挂0面较大且新人集中挂0，反映新人训练与经理陪谈覆盖不足，Top成交打法尚未复制。";else if(cm.zero/cm.people>.5)diagnosis="老人挂0面偏大，更可能是执行松懈、客户筛选过早或原有打法失效，需抽查过程记录。";else if(cm.revenue>0&&top2/cm.revenue>.6)diagnosis="营收集中在少数销售，当前改善尚未形成团队复制。";else diagnosis="团队效率接近大盘，建议继续观察完课后方案输出、破壳和多科拓展。";return{name,base,grade:[...new Set(cr.map(r=>r.grade))].join("/"),orders:cm.orders,share:baseOrders?cm.orders/baseOrders:0,ltv:cm.ltv,previousLtv:pm.ltv,arrival:cm.arrival,attendance:cm.attendance,completion:cm.completion,headConv:cm.headConv,previousHeadConv:pm.headConv,zero:cm.zero,people:cm.people,newcomers:newSales.length,newcomerZero,continuing:continuing2.size,top2Share:cm.revenue?top2/cm.revenue:0,impact,repeatDrag,cohort2:cohortMetric(cr,continuing2),cohort3:continuing3?cohortMetric(cr,continuing3):null,newTeam:cohortMetric(cr,newTeam),diagnosis}}).sort((a,b)=>Math.abs(b.impact)-Math.abs(a.impact));
 const allPeriods=[...new Set(relevant.map(b=>b.period))].sort((a,b)=>a.localeCompare(b)).slice(-6);const trend=allPeriods.map(period=>({period,bases:Object.fromEntries(bases.map(base=>[base,metric(relevant.filter(b=>b.period===period).flatMap(b=>b.rows).filter(r=>r.base===base)).ltv]))}));
 // 复盘阈值：绝对差值15以内为基本持平，避免将正常波动强行归因到团队。
 const delta=current.ltv-previous.ltv,isImproving=delta>15,isDeclining=delta< -15;
 const baseMetrics=bases.map(base=>({base,c:metric(curRows.filter(r=>r.base===base)),p:metric(preRows.filter(r=>r.base===base))})).sort((a,b)=>(b.c.ltv-b.p.ltv)-(a.c.ltv-a.p.ltv));
 // 经理列表按影响规模展示；结论则随整体方向切换为“找增量”或“找拖累”。
 const positiveManagers=managers.filter(m=>m.impact>0),negativeManagers=managers.filter(m=>m.impact<0);
 const drivers=(isImproving?positiveManagers:isDeclining?negativeManagers:[]).sort((a,b)=>isImproving?b.impact-a.impact:a.impact-b.impact);
 const leader=drivers[0];
 const primaryBase=isImproving?baseMetrics.find(x=>x.c.ltv>x.p.ltv):isDeclining?[...baseMetrics].reverse().find(x=>x.c.ltv<x.p.ltv):undefined;
 const positiveLeader=[...positiveManagers].sort((a,b)=>b.impact-a.impact)[0],negativeLeader=[...negativeManagers].sort((a,b)=>a.impact-b.impact)[0],positiveBase=baseMetrics.find(x=>x.c.ltv>x.p.ltv),negativeBase=[...baseMetrics].reverse().find(x=>x.c.ltv<x.p.ltv);
 const processDelta=(c:number|null,p:number|null)=>c==null||p==null?null:c-p,teamLabel=(name:string)=>name.endsWith("团队")?name:`${name}团队`;
 const summary=isImproving
  ?`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）提升${fmt(delta)}，核心拉动来自${primaryBase?primaryBase.base:"各基地"}；优先复盘增量团队的转化动作与可复制性。`
  :isDeclining
   ?`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）下滑${fmt(Math.abs(delta))}，${primaryBase?`主要拖累来自${primaryBase.base}；需优先定位承接与关单断点。`:'未识别到基地LTV下滑，整体回落更可能来自年级或团队承接结构变化，需核查单量迁移。'}`
   :`整体LTV（${fmt(previous.ltv)} → ${fmt(current.ltv)}）基本持平（差值${fmt(Math.abs(delta))}），${positiveBase&&negativeBase?`${positiveBase.base}LTV回升（${fmt(positiveBase.p.ltv)} → ${fmt(positiveBase.c.ltv)}）与${negativeBase.base}LTV回落（${fmt(negativeBase.p.ltv)} → ${fmt(negativeBase.c.ltv)}）相互抵消。`:positiveBase?`${positiveBase.base}回升是主要正向变化，其他基地基本抵消。`:negativeBase?`${negativeBase.base}回落是主要负向变化，其他基地基本抵消。`:"各基地变化有限，继续观察年级和团队分化。"}`;
 const processChanges=[['到课率',processDelta(current.arrival,previous.arrival)],['出勤率',processDelta(current.attendance,previous.attendance)],['完课率',processDelta(current.completion,previous.completion)] as const];
 const improvedProcess=processChanges.filter(([,v])=>v!=null&&v>0.005).map(([name,v])=>`${name}+${(v!*100).toFixed(1)}pp`).join('、');
 const declinedProcess=processChanges.filter(([,v])=>v!=null&&v< -0.005).map(([name,v])=>`${name}${(v!*100).toFixed(1)}pp`).join('、');
 const userText=isImproving
  ?`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。${improvedProcess?`${improvedProcess}，为课后转化提供了更多有效触点。`:declinedProcess?`前端过程未同步改善（${declinedProcess}），本期提升更可能来自课后成交效率或产品组合，需结合录音、追单与客单数据验证。`:'前端过程基本稳定，提升原因应继续下探至课后破壳和关单动作。'}`
  :isDeclining
   ?`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。${declinedProcess?`过程回落集中在${declinedProcess}，需优先检查首次触达、课程价值塑造与开课提醒。`:'前端过程未明显恶化，问题更可能集中在完课后的破壳与关单。'}`
   :`到课率（${pct(previous.arrival)} → ${pct(current.arrival)}）、出勤率（${pct(previous.attendance)} → ${pct(current.attendance)}）、完课率（${pct(previous.completion)} → ${pct(current.completion)}）。整体基本持平不代表内部无变化，应结合回升/下滑基地分别检查前端承接与课后破壳，避免正负变化被整体均值掩盖。`;
 const salesText=leader?isImproving
  ?`${leader.base}${teamLabel(leader.name)}是本期核心增量：LTV（${fmt(leader.previousLtv)} → ${fmt(leader.ltv)}），人头转化（${pct(leader.previousHeadConv,2)} → ${pct(leader.headConv,2)}），承接基地${pct(leader.share)}单量。${leader.headConv>leader.previousHeadConv?`破壳率提升是直接贡献，需重点复盘该团队在需求诊断、方案输出、异议处理和持续追单上的具体打法。`:`人头转化未同步提升，LTV增量更可能来自客单或产品组合；需结合成交明细验证，避免将少数大单误判为团队能力提升。`}${leader.top2Share>.6?' 营收仍集中在少数销售，后续需验证打法是否已复制。':''}`
  :`${leader.base}${teamLabel(leader.name)}是本期主要拖累：LTV（${fmt(leader.previousLtv)} → ${fmt(leader.ltv)}），人头转化（${pct(leader.previousHeadConv,2)} → ${pct(leader.headConv,2)}），承接基地${pct(leader.share)}单量，${leader.people}人中${leader.zero}人挂0，其中新人${leader.newcomers}人、新人挂0 ${leader.newcomerZero}人。${leader.diagnosis}`
  :isDeclining?"经理团队LTV均未下滑，不能归因为单个团队拖累；整体回落更可能由低LTV年级/团队承接量上升或上期高LTV团队单量收缩导致，需优先核查承接结构。":positiveLeader&&negativeLeader?`整体基本持平，但内部由正负团队对冲：${positiveLeader.base}${teamLabel(positiveLeader.name)}回升（LTV ${fmt(positiveLeader.previousLtv)} → ${fmt(positiveLeader.ltv)}，承接${pct(positiveLeader.share)}单量）是主要正向贡献；${negativeLeader.base}${teamLabel(negativeLeader.name)}下滑（LTV ${fmt(negativeLeader.previousLtv)} → ${fmt(negativeLeader.ltv)}，承接${pct(negativeLeader.share)}单量）是主要拖累。需分别复盘前者的可复制打法与后者的漏斗断点。`:positiveLeader?`${positiveLeader.base}${teamLabel(positiveLeader.name)}回升（LTV ${fmt(positiveLeader.previousLtv)} → ${fmt(positiveLeader.ltv)}）是本期主要正向变化；尚未识别明确下滑团队，需结合承接结构继续核查。`:negativeLeader?`${negativeLeader.base}${teamLabel(negativeLeader.name)}下滑（LTV ${fmt(negativeLeader.previousLtv)} → ${fmt(negativeLeader.ltv)}）是本期主要负向变化；尚未识别明确回升团队，需结合承接结构继续核查。`:"整体LTV差值在15以内，团队变化也有限，继续观察下期变化。";const fullText=`整体数据总结：${summary}\n\n用户侧：${userText}\n\n销售侧：${salesText}`;
 return{channel,currentPeriod,previousPeriod,current,previous,gradeLines,managers:managers.slice(0,8),trend,bases,summary,userText,salesText,fullText,warnings:[...new Set(relevant.flatMap(b=>b.warnings))]};
}

export const format={number:(n:number)=>Math.round(n).toLocaleString("zh-CN"),decimal:(n:number)=>fmt(n),percent:(n:number|null,d=1)=>pct(n,d)};
