"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import * as XLSX from "xlsx";
import {toPng} from "html-to-image";
import {buildReview,format,LoadedBook,parseWorkbook,ReviewResult} from "./analysis";

const demo:ReviewResult={channel:"CPA19",currentPeriod:"0813期",previousPeriod:"0806期",current:{orders:3439,revenue:397558,ltv:115.6,arrival:.467,attendance:.379,completion:.131,headConv:.0198,timesConv:.037,people:91,zero:52},previous:{orders:3760,revenue:573024,ltv:152.4,arrival:.588,attendance:.49,completion:.188,headConv:.0312,timesConv:.051,people:86,zero:37},gradeLines:[{base:"成都",grade:"新高一",orders:468,share:.39,newcomers:5,people:10,newcomerRate:.5,ltv:67,attendance:.35},{base:"成都",grade:"新高二",orders:412,share:.34,newcomers:6,people:24,newcomerRate:.25,ltv:116,attendance:.41},{base:"成都",grade:"新高三",orders:334,share:.28,newcomers:2,people:11,newcomerRate:.182,ltv:177,attendance:.36},{base:"成都",grade:"总计",orders:1214,share:1,newcomers:13,people:45,newcomerRate:.289,ltv:123,attendance:.37},{base:"郑州",grade:"新高一",orders:484,share:.22,newcomers:1,people:21,newcomerRate:.048,ltv:92,attendance:.38},{base:"郑州",grade:"新高二",orders:1100,share:.49,newcomers:1,people:12,newcomerRate:.083,ltv:93,attendance:.4},{base:"郑州",grade:"新高三",orders:641,share:.29,newcomers:0,people:13,newcomerRate:0,ltv:146,attendance:.41},{base:"郑州",grade:"总计",orders:2225,share:1,newcomers:2,people:46,newcomerRate:.043,ltv:117,attendance:.4}],managers:[{name:"杨雪雅",base:"郑州",grade:"高一",orders:261,share:.313,ltv:20.5,previousLtv:95.6,arrival:.405,attendance:.301,completion:.102,headConv:.008,previousHeadConv:.023,zero:14,people:15,newcomers:5,newcomerZero:5,continuing:4,top2Share:.74,impact:-19601,repeatDrag:true,cohort2:{people:4,orders:91,ltv:38.2,headConv:.011,zero:3},cohort3:{people:3,orders:64,ltv:42.6,headConv:.012,zero:2},newTeam:{people:11,orders:170,ltv:11.1,headConv:.006,zero:11},diagnosis:"连续两期LTV下滑，且本期新承接销售全部挂0；需优先复盘经理过程追踪、关键节点陪谈与Top打法复制。"}],trend:[{period:"0723期",bases:{成都:151,郑州:118}},{period:"0730期",bases:{成都:139,郑州:129}},{period:"0806期",bases:{成都:153,郑州:116}},{period:"0813期",bases:{成都:138.1,郑州:102.6}}],bases:["成都","郑州"],summary:"整体LTV（152.4 → 115.6）明显下滑，郑州和成都均有回落，主要拖累来自高一年级。",userText:"到课、出勤、完课同步下降，说明首次触达、课程价值塑造和课中陪伴走弱；剩余完课用户也没有被有效转化。",salesText:"郑州杨雪雅团队LTV（95.6 → 20.5），承接基地31.3%单量，15人中14人挂0，其中5名新人均挂0。",fullText:"整体数据总结：整体LTV（152.4 → 115.6）明显下滑，主要拖累来自郑州高一。\n\n用户侧：到课、出勤、完课同步下降，前端过程和课后破壳同时走弱。\n\n销售侧：杨雪雅团队15人中14人挂0，新人训练、经理陪谈和Top打法复制不足。",warnings:[]};

function exportReview(r:ReviewResult){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["渠道",r.channel],["本期",r.currentPeriod],["对比期",r.previousPeriod],["整体LTV",r.current.ltv],["到课率",r.current.arrival],["出勤率",r.current.attendance],["完课率",r.current.completion],["人头转化",r.current.headConv],["复盘文案",r.fullText]]),"复盘摘要");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.gradeLines.map(x=>({基地:x.base,年级:x.grade,单量:x.orders,单量占比:x.share,新人:x.newcomers,销售人数:x.people,新人占比:x.newcomerRate,LTV:x.ltv,出勤率:x.attendance}))),"基地年级");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(r.managers.map(x=>({基地:x.base,经理:x.name,年级:x.grade,连续两期拖累:x.repeatDrag?"是":"否",单量:x.orders,单量占比:x.share,上期LTV:x.previousLtv,本期LTV:x.ltv,人头转化:x.headConv,挂0:x.zero,团队人数:x.people,连续承接2期人数:x.cohort2.people,连续承接2期LTV:x.cohort2.ltv,连续承接3期人数:x.cohort3?.people??"数据不足",连续承接3期LTV:x.cohort3?.ltv??"数据不足",本期新承接人数:x.newTeam.people,本期新承接LTV:x.newTeam.ltv,本期新承接挂0:x.newTeam.zero,Top2营收占比:x.top2Share,问题定位:x.diagnosis}))),"经理下探");XLSX.writeFile(wb,`${r.channel}_${r.currentPeriod}_渠道复盘.xlsx`)}

function processValue(value:number|null,overall:number|null){if(value==null)return "—";const diff=overall==null?"":` · ${value-overall>=0?"+":""}${((value-(overall||0))*100).toFixed(1)}pp`;return `${format.percent(value,1)}${diff}`}
function teamName(name:string){return name.endsWith("团队")?name:`${name}团队`}
function cohortText(label:string,c:{people:number;ltv:number;headConv:number;zero:number}|null){return <div className="cohort-card"><small>{label}</small>{c?<><b>{c.people}人 · LTV {format.decimal(c.ltv)}</b><span>人头 {format.percent(c.headConv,2)} · 挂0 {c.zero}/{c.people}</span></>:<span>未上传上上期，暂无法识别</span>}</div>}

export default function Home(){
 const inputRef=useRef<HTMLInputElement>(null),tableRef=useRef<HTMLElement>(null);const[books,setBooks]=useState<LoadedBook[]>([]),[result,setResult]=useState<ReviewResult>(demo),[running,setRunning]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[channel,setChannel]=useState("CPA19"),[currentPeriod,setCurrentPeriod]=useState("0813期"),[previousPeriod,setPreviousPeriod]=useState("0806期"),[days,setDays]=useState(50),[historyOpen,setHistoryOpen]=useState(false),[managerOpen,setManagerOpen]=useState(false),[history,setHistory]=useState<ReviewResult[]>([]);
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("channel-review-history")||"[]"))}catch{}},[]);
 const channels=useMemo(()=>[...new Set(books.map(b=>b.channel))],[books]),periods=useMemo(()=>[...new Set(books.filter(b=>b.channel===channel||channel==="全部渠道").map(b=>b.period))].sort().reverse(),[books,channel]);
 useEffect(()=>{if(periods.length){setCurrentPeriod(periods[0]);setPreviousPeriod(periods[1]||periods[0])}},[periods.join("|")]);
 const addFiles=async(list:FileList|null)=>{if(!list)return;setError("");setRunning(true);try{const parsed=await Promise.all(Array.from(list).map(parseWorkbook));setBooks(p=>[...p.filter(x=>!parsed.some(n=>n.id===x.id)),...parsed]);const recognized=parsed.find(x=>x.channel!=="未识别渠道");if(recognized)setChannel(recognized.channel);setNotice(`已解析 ${parsed.length} 个文件、${parsed.reduce((s,b)=>s+b.rows.length,0).toLocaleString()} 行销售明细`)}catch(e){setError(e instanceof Error?e.message:"Excel解析失败")}finally{setRunning(false)}};
 const run=()=>{setError("");setRunning(true);try{const r=buildReview(books,currentPeriod,previousPeriod,channel,days);setResult(r);const next=[r,...history.filter(h=>!(h.channel===r.channel&&h.currentPeriod===r.currentPeriod))].slice(0,12);setHistory(next);localStorage.setItem("channel-review-history",JSON.stringify(next));setNotice("分析完成，已保存到历史复盘")}catch(e){setError(e instanceof Error?e.message:"分析失败")}finally{setTimeout(()=>setRunning(false),350)}};
 const copy=async()=>{try{if(navigator.clipboard)await navigator.clipboard.writeText(result.fullText);else throw new Error()}catch{const t=document.createElement("textarea");t.value=result.fullText;t.style.position="fixed";t.style.opacity="0";document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}setNotice("复盘文案已复制")};
 const saveImage=async()=>{if(!tableRef.current)return;try{const url=await toPng(tableRef.current,{pixelRatio:2,backgroundColor:"#fffefa"});const a=document.createElement("a");a.href=url;a.download=`${result.channel}_${result.currentPeriod}_过程数据.png`;a.click();setNotice("过程数据表已保存为图片")}catch{setError("图片生成失败，请重试")}};
 const exportManagers=()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(result.managers.map((m,i)=>({优先级:i+1,基地:m.base,经理:m.name,问题:m.diagnosis,建议动作:"抽查首次触达、完课后方案输出、异议处理和追单记录；安排录音复盘与经理陪谈。",验收指标:"到课率、完课率、破壳率、挂0率、连续追单覆盖"}))),"整改清单");XLSX.writeFile(wb,`${result.channel}_${result.currentPeriod}_经理整改清单.xlsx`)};
 const chartMax=Math.max(200,...result.trend.flatMap(t=>Object.values(t.bases))),chartMin=Math.min(0,...result.trend.flatMap(t=>Object.values(t.bases))),point=(base:string,i:number)=>{const n=Math.max(1,result.trend.length-1),v=result.trend[i]?.bases[base]||0;return`${8+i*(744/n)},${8+(chartMax-v)/(chartMax-chartMin||1)*160}`};
 const totalNew=result.gradeLines.filter(x=>x.grade==="总计").reduce((s,x)=>s+x.newcomers,0),totalPeople=result.gradeLines.filter(x=>x.grade==="总计").reduce((s,x)=>s+x.people,0);
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">复</span><div><strong>渠道复盘工作台</strong><small>销售转化智能分析</small></div></div><div className="top-actions"><span className="status-dot">本地分析 · 数据不外传</span><button className="ghost" onClick={()=>setHistoryOpen(true)}>历史复盘</button><span className="avatar">胜利</span></div></header>
 <section className="hero"><div><p className="eyebrow">CHANNEL REVIEW · {result.currentPeriod}</p><h1>上传底表，得到一份<br/><em>能解释“为什么”的复盘</em></h1><p>自动去重销售、计算新人占比，下探至基地、年级、经理与具体销售动作。</p></div><div className="hero-summary"><span>本期结论</span><strong>{result.summary.split("，")[0]}</strong><p>{result.salesText.slice(0,54)}…</p></div></section>
 <div className="workspace"><aside className="control-panel"><div className="panel-title"><span>01</span><div><b>导入数据</b><small>至少上传本期与上期底表</small></div></div><div className="dropzone" onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><input ref={inputRef} type="file" accept=".xlsx,.xls,.csv" multiple hidden onChange={e=>addFiles(e.target.files)}/><div className="upload-icon">↑</div><b>拖拽底表到这里</b><span>或点击选择文件</span><small>支持多期、多工作表和合并单元格</small></div><div className="file-list">{books.map(b=><div className="file" key={b.id}><span className="excel">X</span><div><b>{b.name}</b><small>{b.period} · {b.rows.length.toLocaleString()}行 · {b.channel}</small></div><button aria-label={`移除${b.name}`} onClick={()=>setBooks(books.filter(x=>x.id!==b.id))}>×</button></div>)}</div>
 <div className="panel-title compact"><span>02</span><div><b>复盘口径</b></div></div><label>渠道<select value={channel} onChange={e=>setChannel(e.target.value)}>{(channels.length?channels:["CPA19","CPA1元","CPA0-9"]).map(x=><option key={x}>{x}</option>)}</select></label><div className="field-row"><label>本期<select value={currentPeriod} onChange={e=>setCurrentPeriod(e.target.value)}>{(periods.length?periods:["0813期","0806期"]).map(x=><option key={x}>{x}</option>)}</select></label><label>对比期<select value={previousPeriod} onChange={e=>setPreviousPeriod(e.target.value)}>{(periods.length?periods:["0806期"]).map(x=><option key={x}>{x}</option>)}</select></label></div><label>新人定义<div className="input-suffix"><input type="number" min="0" max="365" value={days} onChange={e=>setDays(Number(e.target.value)||50)}/><span>天以内</span></div></label><label className="check"><input type="checkbox" defaultChecked disabled/>销售跨年级自动去重</label><button className="primary" onClick={run} disabled={running||periods.length<2}>{running?<><i/>正在解析与计算…</>:"生成渠道复盘"}</button>{books.length>0&&periods.length<2&&<p className="error-msg">请再上传一个不同期次的同渠道底表</p>}{error&&<p className="error-msg">{error}</p>}{notice&&<p className="success-msg">{notice}</p>}<p className="privacy">Excel仅在当前浏览器中处理，不上传服务器</p></aside>
 <section className="report"><div className="report-head"><div><span className="pill">{result.channel} · {result.currentPeriod}{books.length?"":" · 示例"}</span><h2>渠道转化复盘</h2><p>对比{result.previousPeriod} · 新人口径{days}天</p></div><div className="report-actions"><button onClick={copy}>复制文案</button><button className="export" onClick={()=>exportReview(result)}>导出复盘表 ↓</button></div></div>
 <div className="metric-grid">{[{label:"整体 LTV",value:format.decimal(result.current.ltv),delta:`${result.current.ltv-result.previous.ltv>=0?"+":""}${format.decimal(result.current.ltv-result.previous.ltv)}`},{label:"到课率",value:format.percent(result.current.arrival),delta:`上期 ${format.percent(result.previous.arrival)}`},{label:"人头转化",value:format.percent(result.current.headConv,2),delta:`上期 ${format.percent(result.previous.headConv,2)}`},{label:"新人占比",value:format.percent(totalNew/Math.max(1,totalPeople)),delta:`${totalNew} / ${totalPeople}人`}].map((m,i)=><article key={m.label}><span>{m.label}</span><strong className="metric-value">{m.value}</strong><small className={i<3&&result.current.ltv<result.previous.ltv?"down":"plain"}>{m.delta}</small></article>)}</div>
 <article className="insight-card lead"><div className="insight-label"><span>AI</span>整体数据总结</div><p>{result.summary}</p><div className="evidence"><span>结论证据</span>整体单量 {format.number(result.current.orders)} · 营收 {format.number(result.current.revenue)} · 挂0 {result.current.zero}/{result.current.people}人</div></article><div className="two-col"><article className="insight-card"><div className="insight-label"><span>用</span>用户侧</div><p>{result.userText}</p><ul><li>到课 <b>{format.percent(result.previous.arrival)} → {format.percent(result.current.arrival)}</b></li><li>完课 <b>{format.percent(result.previous.completion)} → {format.percent(result.current.completion)}</b></li></ul></article><article className="insight-card"><div className="insight-label"><span>销</span>销售侧</div><p>{result.salesText}</p><ul><li>挂0 <b>{result.current.zero}/{result.current.people}人</b></li><li>人头 <b>{format.percent(result.previous.headConv,2)} → {format.percent(result.current.headConv,2)}</b></li></ul></article></div>
 <section className="data-section process-card" ref={tableRef}><div className="section-heading"><div><span>分基地 · 分年级</span><h3>新人及过程数据</h3></div><div className="section-note"><small>入职{days}天内 · 销售姓名去重</small><button className="image-button" onClick={saveImage}>保存为图片</button></div></div><div className="table-wrap process-table-wrap"><table className="process-table"><thead><tr><th>基地</th><th>年级</th><th>单量</th><th>单量占比</th><th>新人占比</th><th>LTV</th><th>出勤率</th></tr></thead><tbody>{result.gradeLines.map((x,i)=><tr key={`${x.base}-${x.grade}`} className={x.grade==="总计"?"total-row":""}>{i===0||result.gradeLines[i-1].base!==x.base?<td rowSpan={result.gradeLines.filter(y=>y.base===x.base).length} className="base-cell"><b>{x.base}</b></td>:null}<td>{x.grade}</td><td>{format.number(x.orders)}</td><td>{format.percent(x.share,0)}</td><td className="newcomer-cell">{x.newcomers} / {x.people} · {format.percent(x.newcomerRate)}</td><td>{format.decimal(x.ltv)}</td><td>{format.percent(x.attendance,0)}</td></tr>)}</tbody></table></div><p className="table-caption">表内人数按销售姓名去重，基地总计自动消除跨年级重复。</p></section>
 <section className="data-section"><div className="section-heading"><div><span>重点下探</span><h3>经理问题定位</h3></div><small>按影响规模排序 · 过程数据均按单量加权</small></div>{result.managers.some(m=>m.repeatDrag)&&<div className="repeat-drag-alert"><b>连续两期拖累团队</b><span>{result.managers.filter(m=>m.repeatDrag).map(m=>`${m.base}${teamName(m.name)}`).join("、")}：LTV连续下滑，优先复盘。</span></div>}<div className="manager-list">{result.managers.map((m,i)=><div className="manager" key={`${m.base}-${m.name}`}><span className="rank">{String(i+1).padStart(2,"0")}</span><div className="manager-name"><b>{teamName(m.name)} {m.repeatDrag&&<em>连续拖累</em>}</b><small>{m.base} · {m.grade}</small></div><div className="bar"><i style={{width:`${Math.min(100,Math.abs(m.impact)/(Math.max(...result.managers.map(x=>Math.abs(x.impact)),1))*100)}%`}}/></div><div><small>团队LTV</small><b>{format.decimal(m.previousLtv)} → {format.decimal(m.ltv)}</b></div><div><small>承接量 / 占比</small><b>{format.number(m.orders)} / {format.percent(m.share)}</b></div><div><small>挂0</small><b className="danger">{m.zero}/{m.people}</b></div><div className="manager-process"><span>到课 <b>{processValue(m.arrival,result.current.arrival)}</b></span><span>出勤 <b>{processValue(m.attendance,result.current.attendance)}</b></span><span>完课 <b>{processValue(m.completion,result.current.completion)}</b></span><span>人头 <b>{processValue(m.headConv,result.current.headConv)}</b></span></div><div className="manager-cohorts">{cohortText("连续承接2期",m.cohort2)}{cohortText("连续承接3期",m.cohort3)}{cohortText("本期新承接",m.newTeam)}</div><p className="manager-diagnosis">{m.diagnosis}</p></div>)}</div></section>
 <div className="next-step"><b>下一步建议</b><p>{result.managers[0]?.diagnosis||"继续观察过程与成交变化。"}</p><button onClick={()=>setManagerOpen(true)}>生成经理整改清单 →</button></div>
 <section className="trend-section"><div className="section-heading"><div><span>基地趋势</span><h3>近多期整体 LTV 走势</h3></div><div className="trend-legend">{result.bases.map((b,i)=><span key={b}><i className={i%2===0?"chengdu":"zhengzhou"}/>{b}</span>)}</div></div><div className="trend-chart"><div className="y-labels"><span>{Math.round(chartMax)}</span><span>{Math.round((chartMax+chartMin)/2)}</span><span>{Math.round(chartMin)}</span></div><div className="chart-area"><div className="grid-line g1"/><div className="grid-line g2"/><div className="grid-line g3"/><svg className="trend-svg" viewBox="0 0 760 180" role="img" aria-label="基地近多期LTV连续折线图">{result.bases.map((b,bi)=><g key={b}><polyline className={`series-line ${bi%2===0?"chengdu-series":"zhengzhou-series"}`} points={result.trend.map((_,i)=>point(b,i)).join(" ")}/>{result.trend.map((_,i)=>{const[x,y]=point(b,i).split(",").map(Number);return <circle key={i} className={`series-point ${bi%2===0?"chengdu-point":"zhengzhou-point"}`} cx={x} cy={y} r="5"/>})}</g>)}</svg><div className="x-labels">{result.trend.map(t=><span key={t.period}>{t.period}</span>)}</div></div><div className="trend-callout"><b>本期基地差距</b><strong>{result.bases.length>1?format.decimal(Math.abs((result.trend.at(-1)?.bases[result.bases[0]]||0)-(result.trend.at(-1)?.bases[result.bases[1]]||0))):"—"}</strong><span>{result.bases.map(b=>`${b} ${format.decimal(result.trend.at(-1)?.bases[b]||0)}`).join(" · ")}</span></div></div></section></section></div>
 {historyOpen&&<div className="modal-backdrop" onClick={()=>setHistoryOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h3>历史复盘</h3><button onClick={()=>setHistoryOpen(false)}>×</button></div>{history.length?<div className="history-list">{history.map((h,i)=><button key={`${h.channel}-${h.currentPeriod}-${i}`} onClick={()=>{setResult(h);setHistoryOpen(false)}}><b>{h.channel} · {h.currentPeriod}</b><span>LTV {format.decimal(h.current.ltv)} · 对比{h.previousPeriod}</span></button>)}</div>:<p className="empty-state">生成复盘后会自动保存在本机浏览器。</p>}</section></div>}
 {managerOpen&&<div className="modal-backdrop" onClick={()=>setManagerOpen(false)}><section className="modal wide-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h3>经理整改清单</h3><button onClick={()=>setManagerOpen(false)}>×</button></div><div className="rectify-list">{result.managers.slice(0,5).map((m,i)=><article key={m.name}><span>{i+1}</span><div><b>{m.base} · {m.name}团队</b><p>{m.diagnosis}</p><small>验收：到课率、完课率、破壳率、挂0率、持续追单覆盖</small></div></article>)}</div><button className="primary" onClick={exportManagers}>导出整改清单 Excel</button></section></div>}
 </main>
}
